/* APS Field App – SANS quick tips (data + screen). Every tip is "guide only". chk:1 = a number or rule to double-check in the current standard. */
var APS_TIP_TOPICS=[['support','Supports & sleeves'],['fall','Falls & drains'],['vent','Venting & traps'],['geyser','Geysers & hot water'],['valve','Valves & backflow'],['pressure','Pressure & testing'],['material','Pipe materials'],['access','Access & stormwater'],['cert','Certificates & rules']];
var APS_TIPS=[
{id:'t-sup1',topic:'support',t:'Support pipes close to every fitting and change of direction',b:'Clip near each valve, tee, bend and appliance so the fitting does not carry the weight of the pipe. Use rubber-lined clips so metal does not rattle or rub.',ref:'SANS 10252-1 (supports)',kw:'clip bracket sag rattle noisy support',sc:'pipe-supports-sleeving'},
{id:'t-sup2',topic:'support',t:'Typical clip spacing (trade values)',b:'As rule-of-thumb trade values: uPVC up to 50 mm about 0.6 m horizontal and 1.5 m vertical; copper 15 mm about 1.2 m horizontal and 1.8 m vertical; copper 22 to 28 mm about 1.8 m horizontal and 2.4 m vertical. These are not quoted from the standard.',ref:'Trade practice; SANS 10252-1/-2',chk:1,kw:'spacing distance between clips metres horizontal vertical support',sc:'pipe-supports-sleeving'},
{id:'t-sup3',topic:'support',t:'Allow for expansion on long hot runs',b:'Copper grows about 0.017 mm per metre for each degree of temperature rise. Use loops, offsets or sliding clips on long hot runs so the pipe can move. Plastic pipes move several times more than copper.',ref:'Material data; SANS 10252-1',chk:1,kw:'expansion contraction movement loop thermal copper plastic',sc:'pipe-supports-sleeving'},
{id:'t-sup4',topic:'support',t:'Sleeve pipes through walls and slabs',b:'A sleeve lets the pipe move and be replaced without breaking the wall. Do not bury unprotected pipe in concrete or plaster, and keep joints out of the wall or slab.',ref:'SANS 10252-1',kw:'sleeve sleeving wall slab concrete bury cast in',sc:'pipe-supports-sleeving'},
{id:'t-fall1',topic:'fall',t:'Minimum fall on waste and soil pipes',b:'SANS 10252-2 Table 15 gives minimum falls of 1:46 for waste branches and 1:40 for soil branches (guide only, check the table for each size). 1:46 is about 21.7 mm drop per metre; 1:40 is 25 mm per metre.',ref:'SANS 10252-2, Table 15',chk:1,kw:'fall gradient slope waste soil 1:46 1:40 mm per metre',sc:'fall-on-waste-pipes'},
{id:'t-fall2',topic:'fall',t:'Site practice is not the standard',b:'A site habit of 1:40 for 50 mm and 1:60 for 110 mm is not the standard fall. Do not quote it to a customer or inspector.',ref:'SANS 10252-2',kw:'fall 1:60 110mm 50mm site practice wrong',sc:'fall-on-waste-pipes'},
{id:'t-fall3',topic:'fall',t:'Never reduce the pipe size downstream on a drain',b:'A drain must stay the same size or get bigger in the direction of flow. Reducing it creates a place for solids to catch and block. A WC needs a 110 mm soil pipe.',ref:'SANS 10252-2',kw:'reduce size smaller pipe downstream wc 110mm blockage',sc:'blocked-drain'},
{id:'t-fall4',topic:'fall',t:'Use two 45 degree bends, not one 90',b:'Two 45 degree bends (or a long-radius bend) let solids flow better than a sharp 90 degree elbow. Keep the number of bends low.',ref:'Good practice; SANS 10252-2',kw:'bend 45 90 elbow swept drain flow blockage',sc:'blocked-sewer-manhole'},
{id:'t-fall5',topic:'fall',t:'Typical waste pipe sizes',b:'As a typical guide: basin 40 mm, bath and shower 50 mm, WC 110 mm. Check the standard for the size to use for each fixture and for the number of fixtures on a branch.',ref:'SANS 10252-2',chk:1,kw:'waste size 40 50 110 basin bath shower wc diameter',sc:'venting-aav'},
{id:'t-vent1',topic:'vent',t:'Every fixture needs a trap with a water seal',b:'A trap stops sewer gas entering the building. Do not put two traps in series on one fixture (double trapping). Check the required seal depth in the current standard (commonly around 50 mm).',ref:'SANS 10252-2',chk:1,kw:'trap seal depth water seal double trapping smell',sc:'trap-smell-basin-waste'},
{id:'t-vent2',topic:'vent',t:'Keep the trap close to a vent',b:'A trap too far from a vent can siphon its water out and smell. A common rule of thumb is up to about 6 m for a basin waste and about 10 m for larger fixtures. Check the table in the standard for the pipe size and fall.',ref:'SANS 10252-2',chk:1,kw:'vent distance 6m 10m siphon trap gurgling',sc:'venting-aav'},
{id:'t-vent3',topic:'vent',t:'Air admittance valves need approval and access',b:'An AAV lets air in but never out. Fit it in an accessible, ventilated spot above the flood level of the fixture it serves. It is not accepted everywhere: check the municipality, and never make it the only vent on the whole system.',ref:'SANS 10252-2; by-laws',chk:1,kw:'aav air admittance valve studor durgo vent municipality',sc:'venting-aav'},
{id:'t-vent4',topic:'vent',t:'Open vents must end in a safe place',b:'Vent pipe outlets must be above the roof and clear of windows and air intakes so sewer gas cannot blow into the building. Check the required heights in the standard.',ref:'SANS 10252-2',chk:1,kw:'vent pipe roof outlet window height smell',sc:'sewer-smell-dry-trap'},
{id:'t-vent5',topic:'vent',t:'Seldom-used traps dry out',b:'A trap that is not used for weeks can lose its water seal by evaporation and then smell. Run water into floor drains and guest bathrooms regularly. A little oil on top slows evaporation.',ref:'Good practice',kw:'dry trap evaporate floor drain guest bathroom smell',sc:'sewer-smell-dry-trap'},
{id:'t-gey1',topic:'geyser',t:'The geyser needs a safety valve with a visible drain',b:'The temperature and pressure safety valve must match the geyser pressure rating (geysers are made for set ratings such as 400 or 600 kPa). Its drain pipe must have no valve or restriction, must fall continuously and must discharge where it can be seen.',ref:'SANS 10254; SANS 10252-1',chk:1,kw:'safety valve t&p relief drain pipe 400kpa 600kpa discharge',sc:'geyser-valves-tray'},
{id:'t-gey2',topic:'geyser',t:'A drip tray is needed where a leak can damage the building',b:'A geyser in a ceiling or above living space needs a drip tray under it with a drain pipe to a safe visible place. The tray must be large enough and the drain not blocked.',ref:'SANS 10254',kw:'drip tray ceiling geyser drain leak damage',sc:'geyser-valves-tray'},
{id:'t-gey3',topic:'geyser',t:'Store hot water at about 60 degrees',b:'Storage around 60 degrees C reduces Legionella risk (bacteria grow in warm water of roughly 25 to 45 degrees C and in dead legs). At the tap, scalds are a risk: a thermostatic mixing valve protects children and the elderly.',ref:'SANS 10252-1; health guidance',chk:1,kw:'legionella 60 degrees thermostat scald tmv temperature bacteria',sc:'hot-too-hot-cold'},
{id:'t-gey4',topic:'geyser',t:'Electric geysers: electrician and CoC',b:'Wiring, elements and thermostats are electrical work for a registered electrician with an Electrical Certificate of Compliance. A plumber makes safe, drains, refills and checks valves. Never switch on a geyser that is not full of water.',ref:'SANS 10142-1; SANS 10254',kw:'electrician coc element thermostat wiring electrical certificate',sc:'geyser-safety-checklist'},
{id:'t-gey5',topic:'geyser',t:'Gas appliances: registered gas installer only',b:'LPG installations follow SANS 10087-1 and need a registered gas installer with a gas Certificate of Conformity. No flames or switches if you smell gas: open windows, close the cylinder valve if safe, leave and call help.',ref:'SANS 10087-1',kw:'gas lpg installer certificate gas smell',sc:'gas-geyser'},
{id:'t-gey6',topic:'geyser',t:'Low-pressure and high-pressure geysers',b:'A low-pressure (vented) geyser has an open vent pipe and is fed from a header tank. A high-pressure (sealed) geyser relies on a safety valve rated for the geyser, a way to handle thermal expansion, and a vacuum breaker or the arrangement the maker shows to stop it being drawn into a vacuum. Read the maker label before choosing valves.',ref:'SANS 10254; maker instructions',chk:1,kw:'low pressure high pressure vented sealed vacuum breaker expansion non-return',sc:'geyser-install'},
{id:'t-gey7',topic:'geyser',t:'New houses and energy rules',b:'SANS 10400-XA asks that a share of the hot water energy in new buildings comes from a source other than direct electric resistance (solar, heat pump or similar). Check the exact rule and the exemptions in the current edition.',ref:'SANS 10400-XA',chk:1,kw:'xa energy solar heat pump new building regulation',sc:'sans-basics'},
{id:'t-gey8',topic:'geyser',t:'Insulate hot pipes and the geyser',b:'Insulating hot pipes and the geyser (blanket) saves energy and stops freezing. Keep the safety valve drain and the valves uncovered and accessible.',ref:'SANS 10254; SANS 10400-XA',kw:'insulation lagging blanket hot pipes energy',sc:'frozen-pipes'},
{id:'t-val1',topic:'valve',t:'Isolating valves at fixtures and appliances',b:'Fit an isolating valve at each fixture and appliance, and one on the geyser feed, so a repair does not mean closing the whole house. Keep valves accessible: not buried in walls or behind tiles.',ref:'SANS 10252-1',kw:'isolating valve angle valve stop appliance accessible',sc:'tap-washer-cartridge'},
{id:'t-val2',topic:'valve',t:'Backflow protection',b:'Dirty water must never be able to flow back into the drinking-water pipe. Use an air gap where you can, or a vacuum breaker or check valve made for the risk: hoses, irrigation, boreholes, tanks, bidets, pools.',ref:'SANS 10252-1; by-laws',kw:'backflow vacuum breaker check valve air gap hose bib irrigation pool bidet cross connection',sc:'backflow-prevention'},
{id:'t-val3',topic:'valve',t:'Never connect a borehole or rainwater tank to the municipal supply',b:'Keep borehole and rainwater systems separate from the municipal pipe. If a tank is topped up from the municipal supply, use an air gap above the high-water level.',ref:'SANS 10252-1; by-laws',kw:'borehole rainwater cross connection top up air gap municipal',sc:'rainwater-harvesting'},
{id:'t-val4',topic:'valve',t:'Valve direction and the flow arrow',b:'Non-return valves, pressure control valves and many strainers only work one way. Follow the arrow on the body and fit them where they can be serviced, with unions or isolating valves either side.',ref:'Maker instructions',kw:'arrow flow direction non-return pcv strainer union',sc:'prv-install'},
{id:'t-val5',topic:'valve',t:'The municipal meter is not yours',b:'The municipal meter and the valve at the boundary belong to the municipality. Do not tamper with them. If the house stopcock will not close, ask the municipality to close the supply.',ref:'Municipal by-laws',kw:'meter boundary valve municipality tamper stopcock',sc:'boundary-stopcock-isolator'},
{id:'t-pr1',topic:'pressure',t:'High supply pressure damages fixtures',b:'Municipal pressure can be higher than fixtures and geysers are rated for. Measure it with a gauge and fit a pressure control valve where it is high. Check the limit in the standard and the ratings on the fixtures.',ref:'SANS 10252-1',chk:1,kw:'high pressure pcv prv kpa regulator hammer noisy dripping',sc:'prv-install'},
{id:'t-pr2',topic:'pressure',t:'Pressure test before closing walls',b:'Test water pipes under pressure and hold the pressure before walls and floors are closed. A common practice is about 1.5 times working pressure for at least 15 minutes. Check the standard for the exact test pressure and time.',ref:'SANS 10252-1',chk:1,kw:'pressure test 1.5 times hold 15 minutes concealed pipes gauge',sc:'hidden-leak-hunt'},
{id:'t-pr3',topic:'pressure',t:'Water-test drains',b:'Fill the drain with water (test plugs at the ends) and watch for a drop in level before covering it. Check the standard for the test head and the time.',ref:'SANS 10252-2',chk:1,kw:'drain test water test plug leak test sewer',sc:'blocked-sewer-manhole'},
{id:'t-pr4',topic:'pressure',t:'Water hammer is a pressure shock',b:'Banging pipes come from fast-closing valves, high pressure or loose pipes. Fit a pressure control valve, secure the pipes, and use an arrestor or a larger pipe loop if needed.',ref:'Good practice; SANS 10252-1',kw:'water hammer banging knocking noise arrestor loose pipe',sc:'noisy-pipes'},
{id:'t-pr5',topic:'pressure',t:'Do not pump directly from the municipal main',b:'Many municipalities do not allow a pump to draw directly from the supply main, because it can starve neighbours. Use a break tank or follow the by-law.',ref:'Municipal by-laws',chk:1,kw:'pump suction main break tank booster by-law',sc:'booster-pump-troubleshoot'},
{id:'t-mat1',topic:'material',t:'Use lead-free solder and flux on drinking water',b:'Capillary joints on potable water must use lead-free solder and a suitable flux. Clean, flux, heat the fitting, and let the solder be drawn in. Never solder a pipe with water in it.',ref:'SANS 10252-1; SANS 460',kw:'solder lead free flux copper capillary potable',sc:'join-copper-solder'},
{id:'t-mat2',topic:'material',t:'Copper tube classes',b:'SANS 460 covers copper tube in classes of wall thickness. Use the class the application and the supplier require, and the matching fittings.',ref:'SANS 460',chk:1,kw:'copper tube class 460 wall thickness',sc:'join-copper-solder'},
{id:'t-mat3',topic:'material',t:'Mixing metals: copper and galvanised',b:'Do not join copper directly to galvanised steel: the dissimilar metals corrode. Use a brass or dielectric transition fitting, and never put copper upstream of galvanised in the water flow.',ref:'Good practice',kw:'dissimilar galvanised copper corrosion dielectric brass',sc:'join-compression-pushfit-solvent'},
{id:'t-mat4',topic:'material',t:'Use fittings and tools of the same make',b:'PEX and multilayer systems use their own press, crimp or compression fittings. Do not mix makes or tools, and keep the pipe out of direct sunlight and away from hot flues.',ref:'Maker instructions',kw:'pex multilayer crimp press fitting mixing makes uv sunlight',sc:'join-pex-multilayer'},
{id:'t-mat5',topic:'material',t:'Solvent weld joints must cure',b:'PVC cement joints need the right primer or cement, an even coat and time to cure before pressure. Ventilate, no flames. Do not use PVC cement for hot water or on other plastics.',ref:'Maker instructions',kw:'pvc cement solvent weld cure primer hot water',sc:'join-compression-pushfit-solvent'},
{id:'t-acc1',topic:'access',t:'Leave rodding eyes and cleaning access',b:'Drains need access at the head of the run, at changes of direction and at junctions so they can be rodded. Never bury a junction without an access point. Check the spacing in the standard.',ref:'SANS 10252-2',chk:1,kw:'rodding eye access cleaning eye inspection manhole junction',sc:'rodding-jetting'},
{id:'t-acc2',topic:'access',t:'Keep valves and joints accessible',b:'Isolating valves, unions and joints in walls should have an access panel. Photograph hidden pipes with a tape measure before they are covered.',ref:'SANS 10252-1; good practice',kw:'access panel valve hidden pipe photo',sc:'job-handover-checklist'},
{id:'t-acc3',topic:'access',t:'Stormwater must not go into the sewer',b:'Roof and yard water goes to the stormwater system or a safe outlet, never into the sewer. Check SANS 10400-R and the by-laws before connecting a downpipe or a gully.',ref:'SANS 10400-R; by-laws',kw:'stormwater storm water sewer gutter downpipe gully',sc:'stormwater-drainage'},
{id:'t-acc4',topic:'access',t:'Never enter a manhole',b:'Sewer gas (hydrogen sulphide) and lack of oxygen kill quickly. You stop smelling it at high concentrations. Work from above with rods; put cones and cover the opening when you leave.',ref:'OHS practice',kw:'manhole confined space gas hydrogen sulphide safety',sc:'blocked-sewer-manhole'},
{id:'t-cert1',topic:'cert',t:'Which certificate for which work',b:'Plumbing work is certified by a licensed (PIRB registered) plumber; electrical work (including geyser wiring) by a registered electrician with an Electrical CoC; gas by a registered gas installer with a gas CoC. A plumber cannot sign an Electrical CoC.',ref:'PIRB; SANS 10142-1; SANS 10087-1',kw:'coc certificate pirb electrician gas installer sign',sc:'coc-plumbing'},
{id:'t-cert2',topic:'cert',t:'Which standard applies',b:'SANS 10252-1 water supply, SANS 10252-2 drainage, SANS 10254 geysers, SANS 10400 building regulations (P drainage, R stormwater, XA energy), SANS 10142-1 wiring, SANS 10087-1 LPG gas, SANS 241 drinking water quality, SANS 460 copper tube.',ref:'SANS list',kw:'which standard sans 10252 10254 10400 10142 10087 241 460',sc:'sans-basics'},
{id:'t-cert3',topic:'cert',t:'Standards change: check the edition',b:'This app gives short reminders, not the standard. Numbers and rules are updated between editions and may differ by municipality. Check the current standard and the municipal by-laws before you rely on a figure.',ref:'All SANS',kw:'edition update guide only check standard by-law',sc:'sans-basics'}
];
(function(){
'use strict';
if(typeof APSF==='undefined')return;
var A=APSF,h=A.h;
function topicName(id){for(var i=0;i<APS_TIP_TOPICS.length;i++)if(APS_TIP_TOPICS[i][0]===id)return APS_TIP_TOPICS[i][1];return id}
function tipText(t){return '*'+t.t+'* (APS Field App)\n'+t.b+'\nRef: '+t.ref+(t.chk?'\nCheck the standard for the exact figure.':'')+'\n\n'+APS_GOF}
function tipCard(t,hlf){
 var c=h('article',{class:'tip','data-tip':t.id});
 var ttl=h('h3',{class:'tt'});if(hlf)ttl.appendChild(hlf(t.t));else ttl.textContent=t.t;
 c.appendChild(h('div',{class:'tmeta'},[h('span',{class:'tp',text:topicName(t.topic)}),t.chk?h('span',{class:'chk-flag','data-flag':'check',text:'Check the standard'}):null]));
 c.appendChild(ttl);
 var body=h('p',{class:'tb'});if(hlf)body.appendChild(hlf(t.b));else body.textContent=t.b;c.appendChild(body);
 c.appendChild(h('div',{class:'tref'},['Ref: '+t.ref+'  ',h('span',{class:'gof',text:APS_GOF})]));
 var b=h('div',{class:'btns'});
 if(t.sc){b.appendChild(h('a',{class:'btn sm',href:'#/book/'+t.sc,'data-act':'tipsc'},[A.ic('book'),'Related guide']))}
 b.appendChild(A.btn('WhatsApp','wa sm',function(){A.doWA(tipText(t))},{'data-act':'tipwa'},'chat'));
 b.appendChild(A.btn('Copy','sm',function(){A.doCopy(tipText(t))},{'data-act':'tipcopy'},'copy'));
 c.appendChild(b);return c}
A.tipCard=tipCard;
A.routes.tips=function(args,q,v){
 A.setBar({title:'SANS quick tips',back:'#/book'});
 if(args[0]){
  var t=null;APS_TIPS.forEach(function(x){if(x.id===args[0])t=x});
  if(t){v.appendChild(tipCard(t));v.appendChild(h('div',{class:'btns'},h('a',{class:'btn pri',href:'#/tips','data-act':'alltips'},'All SANS quick tips')));return}}
 var topic='',query='';
 var inp=h('input',{id:'tq',type:'search',class:'search',placeholder:'Search tips: fall, vent, geyser, valve\u2026',autocomplete:'off',enterkeyhint:'search','aria-label':'Search SANS tips'});
 var chips=h('div',{class:'chips hs',id:'tipchips'}),cnt=h('p',{class:'hint',id:'tipcount'}),list=h('div',{id:'tiplist',class:'tips'});
 v.appendChild(h('div',{class:'note'},[h('b',{text:'Guide only. '}),'Short reminders from the SANS standards, not the standard itself. Tips marked "Check the standard" contain a number or rule that you must confirm in the current edition.']));
 v.appendChild(inp);v.appendChild(chips);v.appendChild(cnt);v.appendChild(list);
 function draw(){
  chips.innerHTML='';
  [['','All ('+APS_TIPS.length+')']].concat(APS_TIP_TOPICS.map(function(x){return [x[0],x[1]+' ('+APS_TIPS.filter(function(t){return t.topic===x[0]}).length+')']})).forEach(function(c){
   chips.appendChild(h('button',{type:'button',class:'chip'+(topic===c[0]?' on':''),'data-topic':c[0],text:c[1],onclick:function(){topic=c[0];draw()}}))});
  list.innerHTML='';
  var items=APS_TIPS.map(function(t){return {t:t}});var hlf=null;
  if(query.trim()&&A.gs){var r=A.gs.search(query,{types:['tip']});items=r.tips;hlf=function(s){return A.gs.hl(s,r.q)}}
  items=items.filter(function(x){return !topic||x.t.topic===topic});
  items.forEach(function(x){list.appendChild(tipCard(x.t,hlf))});
  cnt.textContent=items.length+(items.length===1?' tip':' tips');
  if(!items.length)list.appendChild(h('div',{class:'emptyph',id:'notips',text:'No tip matches. Try another word.'}))}
 inp.addEventListener('input',function(){query=inp.value;draw()});
 draw()};
})();
